### ISSUE TITLE
Add functions to plot the solved networks

### ISSUE THREAD

**Issue by Hazem-IEG** [pypsa-meets-africa/pypsa-earth-sec#41]

**Comment by energyLS** [comment]
I still have some issues plotting the network and making the summary. The rule plot_network requires the script "plot_network_plot_network_pypsa_earth.py" which does not exist (https://github.com/pypsa-meets-africa/pypsa-earth-sec/blob/de43999eae7f1d374a73a8f5672aefc0fa38cb9e/Snakefile#L175). But the output of the rule plot_network is required, because is uses the plotted map as an input (https://github.com/pypsa-meets-africa/pypsa-earth-sec/blob/de43999eae7f1d374a73a8f5672aefc0fa38cb9e/Snakefile#L150). Can you help me with that, @Hazem-IEG? Thanks!

**Comment by Hazem-IEG** [comment]
should work now @energyLS

**Comment by energyLS** [comment]
![grafik](https://user-images.githubusercontent.com/89515385/160803649-14111a29-0c36-44b2-8149-5bbf5f12cf05.png)
specified path didn't work, I had to change it as seen in the first image. Nonetheless, I get another error when starting the rule with snakemake (image 2). Do you have the same issues? If yes, I will try to investigate it later
![grafik](https://user-images.githubusercontent.com/89515385/160803973-c2c9014d-9056-4e24-b5bb-098e1e75fd80.png)

**Comment by Hazem-IEG** [comment]
I see.. I changed the network path now to include the wildcards. So it should work at least when you run the script itself.

For the snakemake issue, what command do you use?

**Comment by energyLS** [comment]
Great, running the script directly works now! 
When trying to run with snakemake I use the following command:
"snakemake -j1 results/MVP_test2/maps/elec_s_4_2030-today.pdf"
it successfully runs the script to a certain point and produces the outputs:
- elec_s_4_-full_topology_2030.pdf and
- elec_s_4_-h2_network_2030.pdf
but raises the error before creating "elec_s_4_2030-today.pdf". Anyways, the error is not too relevant for now, as long as I can reproduce the results running the script directly to be able to investigate the results for the MVP :)
Thanks for the support and fixing.

**Comment by Hazem-IEG** [comment]
Interesting, will look into it later today or tomorrow

**Comment by Hazem-IEG** [comment]
Yes you're right. This is a by product of me merging the branch early as we agreed last time. I will issue a PR shortly with everything fixed ;)
